[default.files]
meal_data_directory = './MealDataFolder'
models = './Models'

[default.features]
features_randomForestClassifier = ['variance','mean', 'median', 'lsam', 'cam','cbm','fft', 'linear_trend','mean_change','time']
features_decisionTreeClassifier = ['median', 'mean', 'sd', 'lsam']
k = 20

[default.classifier]
k_fold = 10
model_dict = [
    ['randomForestClassifier', 'randomForestClassifier.pkl'],
]

