[default.files]
meal_data_directory = './MealDataFolder'
models = './Models'

[default.features_rfc]
features = ['maximum', 'mean', 'sd', 'abs_energy', 'fft']
k = 15

[default.features_dtc]
features = ['median', 'mean', 'sd', 'lsam']
k = 10

[default.features_mlp]
features = ['median', 'mean', 'sd', 'lsam']
k = 20

[default.features_svm]
features = ['median', 'mean', 'sd', 'lsam']
k = 20

[default.classifier]
k_fold = 10
model_dict = [
    ['randomForestClassifier', 'randomForestClassifier.pkl'],
    ['decisionTreeClassifier', 'decisionTreeClassifier.pkl'],
]

